version: '3'

services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
  phpunit:
    image: excercism_php_dev-cli:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit

# Your PHP-cli enviroment

  app:
    container_name: excercism_php
    build:
      context: ./
      dockerfile: dockerfile
    image: excercism_php_dev-cli:latest
    volumes:
      - .:/app
    working_dir: /app